
// Get base se datos
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";


//post base de datos
export const GUARDAR_PRODUCTO = 'GUARDAR_PRODUCTO';
export const GUARDAR_PRODUCTO_EXITO = 'GUARDAR_PRODUCTO_EXITO';
export const GUARDAR_PRODUCTO_ERROR = 'GUARDAR_PRODUCTO_ERROR';

//delete base de datos

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMIANAR_PRODUCTO_ERROR';

//edit base de datos

export const OBTENER_EDITAR = 'OBTENER_EDITAR';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';
